version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/MY-APP
    ports:
      - "8000:8000"
    networks:
      - todonet

  streamlit:
    build:
      context: .
      dockerfile: dockerfile
    command: streamlit run ui.py --server.address=0.0.0.0 --server.port=8501
    volumes:
      - .:/MY-APP
    ports:
      - "8501:8501"
    networks:
      - todonet
    depends_on:
      - fastapi

networks:
  todonet:
